export const colorGreen = '#00AD20'
export const colorGreenShade = '#018c1b'
export const colorNavy = '#090D2B'
export const colorBlue = '#0084F0'
export const colorPink = '#E00B4B'
export const colorOrange = '#F4694B'
export const colorYellow = '#FDBC3C'
export const colorLightYellow = '#FECE71'
export const colorLightGray = '#D3D3D3'
export const colorWhite = '#ffffff'
export const colorError = '#ff0000'

export const colorOrangeBright = '#f1593e'
export const colorOrangeLight = '#f58870'
export const colorBlueShadow = '#0454a1'
export const colorBlueLight = '#3ea8ff'
export const colorNavyLight = '#0f193a'
export const colorNavyDarker = '#030723'

export const colorOrangeStrong = '#e92b16'
